import XCTest
@testable import Advent

final class Day08Test: XCTestCase, IBaseTest {
    let dataTest = """
    ............
    ........0...
    .....0......
    .......0....
    ....0.......
    ......A.....
    ............
    ............
    ........A...
    .........A..
    ............
    ............
    """

    func testPart1() throws {
        check(testValue: 14, day08part1)
    }

    func testPart2() throws {
        check(testValue: 34, day08part2)
    }
}
